import React, { useState, useEffect, useRef } from 'react';
import { ShieldAlert, Server, BarChart3, AlertOctagon, ChevronDown } from 'lucide-react';
import IncidentMap from './IncidentMap';
import PriorityQueue from './PriorityQueue';
import BriefingPanel from './BriefingPanel';
import { getClusters, getQueue } from '../api';

export default function CommandCenter() {
  const [clusters, setClusters] = useState([]);
  const [queue, setQueue] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // Custom map reference state to center map on locate click
  const [mapCenter, setMapCenter] = useState(null);
  const contentRef = useRef(null);

  const scrollToContent = () => {
    contentRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const fetchDashboardData = async (isPoll = false) => {
    if (!isPoll) setLoading(true);
    setError(null);
    try {
      const [clustersData, queueData] = await Promise.all([
        getClusters(),
        getQueue(),
      ]);
      setClusters(clustersData);
      setQueue(queueData);
    } catch (err) {
      setError('Could not connect to FastAPI server. Ensure python app is running.');
    } finally {
      if (!isPoll) setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboardData();
    // Poll data every 10 seconds for real-time dashboard updates
    const interval = setInterval(() => {
      fetchDashboardData(true);
    }, 10000);
    return () => clearInterval(interval);
  }, []);

  const handleLocateIncident = (lat, lng) => {
    setMapCenter([lat, lng]);
  };

  // Live Aggregated Statistics
  const totalOpenIncidents = clusters.length;
  const criticalCount = clusters.filter(c => c.priority === 3).length;
  const totalMergedReports = clusters.reduce((acc, c) => acc + c.count, 0);

  return (
    <div className="portal-page-container animate-fade-in">
      {/* ── COMMAND CENTER BANNER (NIO STYLE) ─────────────────────────────── */}
      <div className="portal-header-banner">
        <div className="portal-banner-content">
          <span className="portal-banner-tag">Intelligent Dispatch Center</span>
          <h1 className="portal-banner-title">CIVIC EMERGENCY COMMAND</h1>
          <p className="portal-banner-desc">
            Real-Time Routing • Smart Geo-Clustering • Automated SLA Tracking
          </p>
        </div>
        <button type="button" className="portal-banner-chevron" onClick={scrollToContent}>
          <ChevronDown size={20} />
        </button>
      </div>

      {/* ── MAIN BODY CONTENT ──────────────────────────────────────────────── */}
      <div ref={contentRef} className="portal-body-wrapper" style={{ maxWidth: '1400px' }}>
        <div className="portal-body-inner" style={{ gap: '30px' }}>
          
          {/* Header Row */}
          <div className="portal-body-header">
            <div className="portal-header-left">
              <h2>
                The Future of
                <br />
                Emergency Operations.
              </h2>
            </div>
            <div className="portal-header-right">
              <p>
                Monitor incoming citizen grievances, analyze real-time spatial clusters, review daily briefings generated by Gemini AI, and dispatch department service crews directly with custom SLA timers.
              </p>
            </div>
          </div>

          {/* Top Stat Cards Grid */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
            gap: '20px'
          }}>
            <div className="cc-stat-card">
              <div className="cc-stat-icon" style={{ background: 'rgba(59, 130, 246, 0.08)', color: '#3b82f6' }}>
                <Server size={20} />
              </div>
              <div style={{ textAlign: 'left' }}>
                <div className="cc-stat-label">Active Clusters</div>
                <strong className="cc-stat-value">{totalOpenIncidents}</strong>
              </div>
            </div>

            <div className="cc-stat-card">
              <div className="cc-stat-icon" style={{ background: '#fef2f2', color: '#ef4444' }}>
                <AlertOctagon size={20} />
              </div>
              <div style={{ textAlign: 'left' }}>
                <div className="cc-stat-label">Critical Dispatches</div>
                <strong className="cc-stat-value" style={{ color: '#ef4444' }}>{criticalCount}</strong>
              </div>
            </div>

            <div className="cc-stat-card">
              <div className="cc-stat-icon" style={{ background: '#f9fafb', color: '#111827' }}>
                <ShieldAlert size={20} />
              </div>
              <div style={{ textAlign: 'left' }}>
                <div className="cc-stat-label">Consolidated Reports</div>
                <strong className="cc-stat-value">{totalMergedReports}</strong>
              </div>
            </div>

            <div className="cc-stat-card">
              <div className="cc-stat-icon" style={{ background: '#ecfdf5', color: '#10b981' }}>
                <BarChart3 size={20} />
              </div>
              <div style={{ textAlign: 'left' }}>
                <div className="cc-stat-label">System Status</div>
                <strong className="cc-stat-value" style={{ color: '#10b981', fontSize: '16px' }}>MONITORED</strong>
              </div>
            </div>
          </div>

          {/* Main Grid split */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'minmax(400px, 500px) 1fr',
            gap: '30px',
            alignItems: 'stretch'
          }}>
            {/* Left Side: Briefing & Table Queue */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
              <BriefingPanel />
              <PriorityQueue queue={queue} onLocateIncident={handleLocateIncident} />
            </div>

            {/* Right Side: Map Card */}
            <div className="portal-map-card" style={{ height: '620px', padding: '16px', display: 'flex', flexDirection: 'column' }}>
              <div className="portal-map-header" style={{ marginBottom: '14px' }}>
                <h3>Incident Location Dispatch Map</h3>
                <p>Live coordinates of classified and routed civic complaint clusters</p>
              </div>
              <div className="portal-map-container-box" style={{ flexGrow: 1, height: '100%' }}>
                <IncidentMap clusters={clusters} center={mapCenter} />
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
